### ISSUE TITLE
ValueError: Unknown layer: IdentityLayer

### ISSUE THREAD

**Issue by d-bohn** [r-tensorflow/autokeras#15]
Hello,

I built my own `autokeras` model, and it successfully ran and created an `autokeras` model. Next, I exported and saved the model via the instructions in the vignette:

```
(keras_model <- export_model(akm1))

# And save the Keras model
keras::save_model_hdf5(keras_model, model_file)
```

However, when I try and reload the model with `my_model <- keras::load_model_hdf5(model_file)` I get the following error:

```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
     ValueError: Unknown layer: IdentityLayer
```
 
Any insight or help would be appreciated!

```
> keras:::keras_version()
[1] ‘2.2.4’
> tensorflow:::tf_version()
[1] ‘2.0’
```

**Comment by jcrodriguez1989** [comment]
Hi @d-bohn , thanks for your report.
Apparently, the autokeras Python library is having issues with the export to Keras function, I have already posted a bug on their repository https://github.com/keras-team/autokeras/issues/929 . Actually, exporting the model to Keras results in useful only to check the NN structure.
In the meantime, I have added two functions to the R autokeras library, `save_model` and `load_model`, these functions will save and restore the AutoKeras model.
Please update your autokeras library with:
```r
remotes::install_github("r-tensorflow/autokeras")
```

**Comment by jcrodriguez1989** [comment]
Hi!
thanks for your comments, I have upgraded `{autokeras}`, could you try with our new version?
thanks!
Install the latest version with:
```r
if (!require("remotes")) {
  install.packages("remotes")
}
remotes::install_github("r-tensorflow/autokeras")
```
