### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :    AttributeError: 'TrackableWeightHandler' object has no attribute 'shape'

### ISSUE THREAD

**Issue by kmuthusi** [r-tensorflow/autokeras#16]
Hi,

Thank you for developing the "autokeras" package. It will definitely be a helpful tool for data scientists. I am trying to run the example for model_structured_data_regressor but I get errors with the 'evaluation' and 'export_model'. It appears that autokeras is unable to select the 'best' trained model

Below is the output of the code and my r session info

Any assistance is highly appreciated

Thank you,

Jacques

> # Predict with the best model
> (predicted_y <- reg %>% predict(test_file_to_predict))
          [,1]
 [1,] 2.564118
 [2,] 2.381873
 [3,] 2.419431
 [4,] 2.604501
 [5,] 2.677018
 [6,] 2.449875
 [7,] 2.924572
 [8,] 2.533927
 [9,] 2.790744
[10,] 2.510988
[11,] 3.068361
[12,] 2.985615
[13,] 2.941829
[14,] 2.945893
[15,] 2.958850
[16,] 2.731235
[17,] 2.757782
[18,] 3.158206
[19,] 2.636754
[20,] 2.885813
[21,] 3.081780
[22,] 3.282970
[23,] 2.709834
[24,] 3.087875
[25,] 3.195198
[26,] 2.692371
[27,] 2.763576
[28,] 2.984694
[29,] 3.079619
[30,] 3.038662
> # Evaluate the best model with testing data
> reg %>% evaluate(test_file_to_eval, "Sepal.Length")
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.

[[1]]
[1] 9.185607
1/1 [==============================] - 0s 67ms/step - loss: 9.1856 - mean_squared_error: 9.1856

[[2]]
[1] 9.185607

> 
> # Get the best trained Keras model, to work with the keras R library
> # export_model(reg)
> 
> (keras_model <- export_model(reg))
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'TrackableWeightHandler' object has no attribute 'shape'
> 

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.14  tfruns_1.4       tensorflow_2.0.0 keras_2.2.5.0    autokeras_1.0.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3      zeallot_0.1.0   rappdirs_0.3.1  R6_2.4.1        jsonlite_1.6.1  magrittr_1.5    whisker_0.4     generics_0.0.2  tools_3.6.3    
[10] xfun_0.12       yaml_2.2.1      compiler_3.6.3  base64enc_0.1-3 knitr_1.28

**Comment by jcrodriguez1989** [comment]
Hi @kmuthusi ,
could you please tell me which Python libraries version are you using? You can check within R with:
```r
reticulate::py_run_string('
import pkg_resources
print(pkg_resources.get_distribution("autokeras").version)
print(pkg_resources.get_distribution("tensorflow").version)
')
```

Anyways, you could try installing the latest `autokeras` version and reinstall autokeras and tensorflow Python libraries.

```r
remotes::install_github("r-tensorflow/autokeras")
library("autokeras")
install_autokeras()
```

**Comment by kmuthusi** [comment]
Hi Juan,

After execution the code

reticulate::py_run_string('
import pkg_resources
print(pkg_resources.get_distribution("autokeras").version)
print(pkg_resources.get_distribution("tensorflow").version)
')

I gwt this output

1.0.2
2.1.0

It is confusing because the classification example runs successfully

Any ideas

Muthusi

**Comment by jcrodriguez1989** [comment]
Please try reinstalling libraries with:
```r
remotes::install_github("r-tensorflow/autokeras")
library("autokeras")
install_autokeras()
```

then, try your example, and again let me know which versions you have now:

```r
reticulate::py_run_string('
import pkg_resources
print(pkg_resources.get_distribution("autokeras").version)
print(pkg_resources.get_distribution("tensorflow").version)
')
```

thanks!

**Comment by kmuthusi** [comment]
Hi,

After I updated and rerun the code, I got this output

> reticulate::py_run_string('
+ import pkg_resources
+ print(pkg_resources.get_distribution("autokeras").version)
+ print(pkg_resources.get_distribution("tensorflow").version)
+ ')
1.0.1
2.1.0

But I get another error

> # Initialize the structured data regressor
>  reg <- model_structured_data_regressor(max_trials = 20) %>% # It tries
10 different models
+   fit(train_file, "Sepal.Length", epochs = 100) # Feed the structured
data regressor with training data
Error: Error loading Python module autokeras

I can no longer initialize the structured data regressor

Not sure how to proceed

Muthusi

**Comment by jcrodriguez1989** [comment]
Have you restarted R/Rstudio and tried again to run the regressor?

**Comment by kmuthusi** [comment]
It is taking back to where I started.

I conclusion it appears there is a bug that needs fixing, so I have decided to wait for the next improved version

-M

**Comment by jcrodriguez1989** [comment]
Hi!
thanks for your comments, I have upgraded `{autokeras}`, could you try with our new version?
thanks!
Install the latest version with:
```r
if (!require("remotes")) {
  install.packages("remotes")
}
remotes::install_github("r-tensorflow/autokeras")
```
