### ISSUE TITLE
Unable to load Autokeras Package in R

### ISSUE THREAD

**Issue by Bmoser-boop** [r-tensorflow/autokeras#18]
I installed Autokeras using Docker and am attempting to use Autokeras in R, but I am unable to load the package.

I used the following commands to download Autokeras:

In terminal:
`docker pull jcrodriguez1989/r-autokeras:0.1.0
docker run -it jcrodriguez1989/r-autokeras:0.1.0 /bin/bash`

After doing this I was able to load the Autokeras package in R, but attempting to run the function model_text_classifier resulted in the following error:

```ImportError: No module named keras
Use the install_keras() function to install the core Keras library
Error: Error loading Python module keras
```

Because of this I tried the Autokeras install function in R:
`remotes::install_github("jcrodriguez1989/autokeras", force=TRUE)`

Since doing this I receive the following error whenever I attempt library(autokeras)
```
Error: package or namespace load failed for ‘autokeras’:
 .onLoad failed in loadNamespace() for 'autokeras', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 'autokeras'
```

I have also noticed that when I run reticulate::py_config() in R I receive the following output:

```
python:         /Users/brianmoser/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/brianmoser/Library/r-miniconda/envs/r-reticulate/lib/libpython3.8.dylib
pythonhome:     /Users/brianmoser/Library/r-miniconda/envs/r-reticulate:/Users/brianmoser/Library/r-miniconda/envs/r-reticulate
version:        3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 02:18:36)  [Clang 10.0.1 ]
numpy:          /Users/brianmoser/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.18.5

```
Although the version says (default, Jul 31 2020) I did not remember having Python 3.8 installed, and my default Python version when opening Python in the terminal is 3.6.10. I also see that Python 3.6.10 is saved in the base environment at /Users/brianmoser/opt/anaconda3/lib/python3.6, but is not saved in /Users/brianmoser/Libraryr-miniconda/envs/r-reticulate/lib/ folder. 

Given all of this information, is there any clear solution to make Autokeras function in R? Is the problem associated with the presence of multiple versions of Python or is it something else?

Additional build info:
OS: macOS High Sierra 10.13.4
R: 3.6.3
RStudio: 1.2.5042

**Comment by jcrodriguez1989** [comment]
Hi!
thanks for your comments, I have upgraded `{autokeras}`, could you try with our new version?
thanks!
Install the latest version with:
```r
if (!require("remotes")) {
  install.packages("remotes")
}
remotes::install_github("r-tensorflow/autokeras")
```

**Comment by cgpeltier** [comment]
I get this same error, running on Windows 10:

`remotes::install_github("r-tensorflow/autokeras")` is successful, but then
```
autokeras::install_autokeras()
Error: .onLoad failed in loadNamespace() for 'autokeras', details:
  call: py_module_import(module, convert = convert)
  error: ImportError: DLL load failed: The specified module could not be found.
```
In case it's helpful:
```
reticulate::py_config()
python:         C:/Users/ChadPeltier/anaconda3/envs/r-reticulate/python.exe
libpython:      C:/Users/ChadPeltier/anaconda3/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/ChadPeltier/anaconda3/envs/r-reticulate
version:        3.6.13 (default, Feb 19 2021, 05:17:09) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/ChadPeltier/anaconda3/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.5
tensorflow:     C:\Users\CHADPE~1\ANACON~1\envs\R-RETI~1\lib\site-packages\tensorflow\__init__.p

python versions found: 
 C:/Users/ChadPeltier/anaconda3/envs/r-reticulate/python.exe
 C:/Users/ChadPeltier/AppData/Local/Programs/Python/Python38/python.exe
 C:/Users/ChadPeltier/anaconda3/python.exe
 C:/Users/ChadPeltier/anaconda3/envs/autokeras/python.exe
 C:/Users/ChadPeltier/anaconda3/envs/janes_data/python.exe
 C:/Users/ChadPeltier/anaconda3/envs/py36/python.exe
 C:/Users/ChadPeltier/anaconda3/envs/testing/python.exe
```
