### ISSUE TITLE
Fix for source code

### ISSUE THREAD

**Issue by abbottken** [r-tensorflow/autokeras#19]
In model_image_classifier.R, model_image_regressor.R, model_structured_data_classifier.R, model_structured_data_regressor.R, model_text_classifier.R, model_text_regressor.R, I had to change the "name" parameter to "project_name" for it to be accepted by Python autokeras 1.0.12. I made these changes to R autokeras 1.0.1 source code and then packed everything back into a tar.gz which I then installed in R.

**Comment by jcrodriguez1989** [comment]
Hi!
thanks for your comments, I have upgraded `{autokeras}`, could you try with our new version?
thanks!
Install the latest version with:
```r
if (!require("remotes")) {
  install.packages("remotes")
}
remotes::install_github("r-tensorflow/autokeras")
```

**Comment by abbottken** [comment]
Thank you! Unfortunately, the (aging) machine I would use to test this is having some issues and I am not sure if/when they will resolve. But thank you for your quick response!

-Ken
________________________________
